Exclude inject from Jax-rs processor in maven (#2050)
We discovered an issue with Micronaut 4.1.1 whilst building the guides:

https://github.com/micronaut-projects/micronaut-guides/pull/1328

Excluding micronaut-inject from the plugin dependency path seems to fix the issue, and we no longer get

https://ge.micronaut.io/s/vrqeirg3xxjoe/failure#1

java.lang.ClassNotFoundException: io.micronaut.core.annotation.Introspected$IntrospectionBuilder